version: '3'

services:
  rabbit:
    restart: always
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_DEFAULT_USER: "rabbit"
      RABBITMQ_DEFAULT_PASS: "rabbit"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"

  flower:
    restart: always
    image: iserko/docker-celery-flower
    ports:
      - "5555:5555"
    environment:
      CELERY_BROKER_URL: amqp://rabbit:rabbit@rabbit:5672
    entrypoint:
      - flower
      - --port=5555
      - --broker_api=http://rabbit:rabbit@rabbit:15672/api/
    depends_on:
      - rabbit
