version: '3'

services:
  rabbit:
    restart: always
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: rabbit
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - "15672:15672"
      - "5672:5672"
  redis:
    restart: always
    image: redis:5.0.5-alpine
    ports:
      - "6379:6379"
  mongo:
    restart: always
    image: mongo:4.2.0-bionic
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
  flower:
    restart: always
    image: mher/flower
    ports:
      - "5555:5555"
    environment:
      CELERY_BROKER_URL: amqp://rabbit:rabbit@rabbit:5672
    entrypoint:
      - flower
      - --port=5555
      - --broker_api=http://rabbit:rabbit@rabbit:15672/api/
    depends_on:
      - rabbit