FROM python:3.7

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY requirements.txt /usr/src/app/

RUN pip install -r requirements.txt
COPY ./server /usr/src/app

EXPOSE 6565
ENTRYPOINT["python"]

CMD["api.py"]
